name: Build And Publish

on:
  push:
    tags:
      - 'release-[0-9]+.[0-9]+.[0-9]+'

jobs:
  buildAndPublish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build
        run: ./gradlew build 

      - name: Sonatype upload
        env: 
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_PWD: ${{ secrets.SONATYPE_PWD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PWD: ${{ secrets.SIGNING_PWD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        run: ./gradlew publishReleasePublicationToMavencentralRepository


